name: CD Clean Air

on:
  push:
    branches:
      - main

jobs:
  DEPLOY:
    name: Deploy Backend (Render)
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
